# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    loaders:
        default:
            flysystem:
                filesystem_service: oneup_flysystem.uploads_filesystem_filesystem
    data_loader: default

    resolvers:
        filesystem_resolver:
            flysystem:
                filesystem_service: oneup_flysystem.uploads_filesystem_filesystem
                root_url:           "%uploads_base_url%"
                cache_prefix:       media/cache
        # default: flysystem_loader
    cache: filesystem_resolver


        

    filter_sets:
        squared_thumbnail_small:
            filters:
                thumbnail:
                    size: [200,200]
                    mode: outbound
                    allow_upscale: true

        squared_thumbnail_medium:
            filters:
                thumbnail:
                    size: [500,500]
                    mode: outbound
                    allow_upscale: true