<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250416073930 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "app_user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_verified BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "app_user" (email)');
        $this->addSql('CREATE TABLE cinema (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, slug VARCHAR(100) NOT NULL, max_rows INT NOT NULL, max_seats_per_row INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, street_name VARCHAR(50) NOT NULL, building_number VARCHAR(10) NOT NULL, postal_code VARCHAR(6) NOT NULL, city VARCHAR(25) NOT NULL, district VARCHAR(30) NOT NULL, country VARCHAR(50) NOT NULL, open_time TIME(0) WITHOUT TIME ZONE NOT NULL, close_time TIME(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D48304B45E237E06 ON cinema (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D48304B4989D9B62 ON cinema (slug)');
        $this->addSql('CREATE INDEX IDX_D48304B47E3C61F9 ON cinema (owner_id)');
        $this->addSql('CREATE TABLE movie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tmdb_id INT DEFAULT NULL, title VARCHAR(100) DEFAULT NULL, duration_in_minutes INT DEFAULT NULL, overview TEXT DEFAULT NULL, release_date DATE DEFAULT NULL, poster_filename VARCHAR(255) DEFAULT NULL, cinema_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1D5EF26FB4CB84B6 ON movie (cinema_id)');
        $this->addSql('CREATE TABLE movie_reference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, filename VARCHAR(255) NOT NULL, original_filename VARCHAR(255) NOT NULL, mime_type VARCHAR(255) NOT NULL, position INT DEFAULT NULL, movie_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3D7640158F93B6FC ON movie_reference (movie_id)');
        $this->addSql('CREATE TABLE movie_screening_format (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, movie_id INT NOT NULL, screening_format_id INT NOT NULL, cinema_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_907F973A8F93B6FC ON movie_screening_format (movie_id)');
        $this->addSql('CREATE INDEX IDX_907F973A80670753 ON movie_screening_format (screening_format_id)');
        $this->addSql('CREATE INDEX IDX_907F973AB4CB84B6 ON movie_screening_format (cinema_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_907F973A8F93B6FCB4CB84B680670753 ON movie_screening_format (movie_id, cinema_id, screening_format_id)');
        $this->addSql('CREATE TABLE reservation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_validated BOOLEAN NOT NULL, showtime_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_42C8495528BE1523 ON reservation (showtime_id)');
        $this->addSql('CREATE TABLE reservation_seat (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(15) NOT NULL, status_locked_expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, showtime_id INT NOT NULL, seat_id INT NOT NULL, reservation_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2B65FB0E28BE1523 ON reservation_seat (showtime_id)');
        $this->addSql('CREATE INDEX IDX_2B65FB0EC1DAFE35 ON reservation_seat (seat_id)');
        $this->addSql('CREATE INDEX IDX_2B65FB0EB83297E7 ON reservation_seat (reservation_id)');
        $this->addSql('CREATE TABLE reset_password_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7CE748AA76ED395 ON reset_password_request (user_id)');
        $this->addSql('CREATE TABLE screening_format (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, language_presentation VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL, visual_format_id INT NOT NULL, cinema_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3A404DABF4D381DB ON screening_format (visual_format_id)');
        $this->addSql('CREATE INDEX IDX_3A404DABB4CB84B6 ON screening_format (cinema_id)');
        $this->addSql('CREATE TABLE screening_room (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, slug VARCHAR(100) NOT NULL, status VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, maintenance_time_in_minutes INT DEFAULT NULL, active BOOLEAN NOT NULL, cinema_id INT DEFAULT NULL, screening_room_setup_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_56558C8D989D9B62 ON screening_room (slug)');
        $this->addSql('CREATE INDEX IDX_56558C8DB4CB84B6 ON screening_room (cinema_id)');
        $this->addSql('CREATE INDEX IDX_56558C8DDBB9A999 ON screening_room (screening_room_setup_id)');
        $this->addSql('CREATE TABLE screening_room_seat (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(15) NOT NULL, type VARCHAR(255) NOT NULL, is_visible BOOLEAN NOT NULL, screening_room_id INT NOT NULL, seat_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8162D5439B3F89 ON screening_room_seat (screening_room_id)');
        $this->addSql('CREATE INDEX IDX_8162D54C1DAFE35 ON screening_room_seat (seat_id)');
        $this->addSql('CREATE TABLE screening_room_setup (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sound_format VARCHAR(50) NOT NULL, is_active BOOLEAN NOT NULL, visual_format_id INT NOT NULL, cinema_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_EDFF4DABF4D381DB ON screening_room_setup (visual_format_id)');
        $this->addSql('CREATE INDEX IDX_EDFF4DABB4CB84B6 ON screening_room_setup (cinema_id)');
        $this->addSql('CREATE TABLE seat (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, row_num INT NOT NULL, seat_num_in_row INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE showtime (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, price INT NOT NULL, advertisement_time_in_minutes INT NOT NULL, slug VARCHAR(255) NOT NULL, is_published BOOLEAN NOT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, screening_room_id INT NOT NULL, movie_screening_format_id INT NOT NULL, cinema_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3248D9139B3F89 ON showtime (screening_room_id)');
        $this->addSql('CREATE INDEX IDX_3248D91B107D596 ON showtime (movie_screening_format_id)');
        $this->addSql('CREATE INDEX IDX_3248D91B4CB84B6 ON showtime (cinema_id)');
        $this->addSql('CREATE TABLE showtime_visual_format (showtime_id INT NOT NULL, visual_format_id INT NOT NULL, PRIMARY KEY(showtime_id, visual_format_id))');
        $this->addSql('CREATE INDEX IDX_138A126428BE1523 ON showtime_visual_format (showtime_id)');
        $this->addSql('CREATE INDEX IDX_138A1264F4D381DB ON showtime_visual_format (visual_format_id)');
        $this->addSql('CREATE TABLE visual_format (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(40) NOT NULL, active BOOLEAN NOT NULL, cinema_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A187A35DB4CB84B6 ON visual_format (cinema_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE cinema ADD CONSTRAINT FK_D48304B47E3C61F9 FOREIGN KEY (owner_id) REFERENCES "app_user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE movie ADD CONSTRAINT FK_1D5EF26FB4CB84B6 FOREIGN KEY (cinema_id) REFERENCES cinema (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE movie_reference ADD CONSTRAINT FK_3D7640158F93B6FC FOREIGN KEY (movie_id) REFERENCES movie (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE movie_screening_format ADD CONSTRAINT FK_907F973A8F93B6FC FOREIGN KEY (movie_id) REFERENCES movie (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE movie_screening_format ADD CONSTRAINT FK_907F973A80670753 FOREIGN KEY (screening_format_id) REFERENCES screening_format (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE movie_screening_format ADD CONSTRAINT FK_907F973AB4CB84B6 FOREIGN KEY (cinema_id) REFERENCES cinema (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C8495528BE1523 FOREIGN KEY (showtime_id) REFERENCES showtime (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reservation_seat ADD CONSTRAINT FK_2B65FB0E28BE1523 FOREIGN KEY (showtime_id) REFERENCES showtime (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reservation_seat ADD CONSTRAINT FK_2B65FB0EC1DAFE35 FOREIGN KEY (seat_id) REFERENCES screening_room_seat (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reservation_seat ADD CONSTRAINT FK_2B65FB0EB83297E7 FOREIGN KEY (reservation_id) REFERENCES reservation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES "app_user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE screening_format ADD CONSTRAINT FK_3A404DABF4D381DB FOREIGN KEY (visual_format_id) REFERENCES visual_format (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE screening_format ADD CONSTRAINT FK_3A404DABB4CB84B6 FOREIGN KEY (cinema_id) REFERENCES cinema (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE screening_room ADD CONSTRAINT FK_56558C8DB4CB84B6 FOREIGN KEY (cinema_id) REFERENCES cinema (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE screening_room ADD CONSTRAINT FK_56558C8DDBB9A999 FOREIGN KEY (screening_room_setup_id) REFERENCES screening_room_setup (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE screening_room_seat ADD CONSTRAINT FK_8162D5439B3F89 FOREIGN KEY (screening_room_id) REFERENCES screening_room (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE screening_room_seat ADD CONSTRAINT FK_8162D54C1DAFE35 FOREIGN KEY (seat_id) REFERENCES seat (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE screening_room_setup ADD CONSTRAINT FK_EDFF4DABF4D381DB FOREIGN KEY (visual_format_id) REFERENCES visual_format (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE screening_room_setup ADD CONSTRAINT FK_EDFF4DABB4CB84B6 FOREIGN KEY (cinema_id) REFERENCES cinema (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE showtime ADD CONSTRAINT FK_3248D9139B3F89 FOREIGN KEY (screening_room_id) REFERENCES screening_room (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE showtime ADD CONSTRAINT FK_3248D91B107D596 FOREIGN KEY (movie_screening_format_id) REFERENCES movie_screening_format (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE showtime ADD CONSTRAINT FK_3248D91B4CB84B6 FOREIGN KEY (cinema_id) REFERENCES cinema (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE showtime_visual_format ADD CONSTRAINT FK_138A126428BE1523 FOREIGN KEY (showtime_id) REFERENCES showtime (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE showtime_visual_format ADD CONSTRAINT FK_138A1264F4D381DB FOREIGN KEY (visual_format_id) REFERENCES visual_format (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE visual_format ADD CONSTRAINT FK_A187A35DB4CB84B6 FOREIGN KEY (cinema_id) REFERENCES cinema (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cinema DROP CONSTRAINT FK_D48304B47E3C61F9');
        $this->addSql('ALTER TABLE movie DROP CONSTRAINT FK_1D5EF26FB4CB84B6');
        $this->addSql('ALTER TABLE movie_reference DROP CONSTRAINT FK_3D7640158F93B6FC');
        $this->addSql('ALTER TABLE movie_screening_format DROP CONSTRAINT FK_907F973A8F93B6FC');
        $this->addSql('ALTER TABLE movie_screening_format DROP CONSTRAINT FK_907F973A80670753');
        $this->addSql('ALTER TABLE movie_screening_format DROP CONSTRAINT FK_907F973AB4CB84B6');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C8495528BE1523');
        $this->addSql('ALTER TABLE reservation_seat DROP CONSTRAINT FK_2B65FB0E28BE1523');
        $this->addSql('ALTER TABLE reservation_seat DROP CONSTRAINT FK_2B65FB0EC1DAFE35');
        $this->addSql('ALTER TABLE reservation_seat DROP CONSTRAINT FK_2B65FB0EB83297E7');
        $this->addSql('ALTER TABLE reset_password_request DROP CONSTRAINT FK_7CE748AA76ED395');
        $this->addSql('ALTER TABLE screening_format DROP CONSTRAINT FK_3A404DABF4D381DB');
        $this->addSql('ALTER TABLE screening_format DROP CONSTRAINT FK_3A404DABB4CB84B6');
        $this->addSql('ALTER TABLE screening_room DROP CONSTRAINT FK_56558C8DB4CB84B6');
        $this->addSql('ALTER TABLE screening_room DROP CONSTRAINT FK_56558C8DDBB9A999');
        $this->addSql('ALTER TABLE screening_room_seat DROP CONSTRAINT FK_8162D5439B3F89');
        $this->addSql('ALTER TABLE screening_room_seat DROP CONSTRAINT FK_8162D54C1DAFE35');
        $this->addSql('ALTER TABLE screening_room_setup DROP CONSTRAINT FK_EDFF4DABF4D381DB');
        $this->addSql('ALTER TABLE screening_room_setup DROP CONSTRAINT FK_EDFF4DABB4CB84B6');
        $this->addSql('ALTER TABLE showtime DROP CONSTRAINT FK_3248D9139B3F89');
        $this->addSql('ALTER TABLE showtime DROP CONSTRAINT FK_3248D91B107D596');
        $this->addSql('ALTER TABLE showtime DROP CONSTRAINT FK_3248D91B4CB84B6');
        $this->addSql('ALTER TABLE showtime_visual_format DROP CONSTRAINT FK_138A126428BE1523');
        $this->addSql('ALTER TABLE showtime_visual_format DROP CONSTRAINT FK_138A1264F4D381DB');
        $this->addSql('ALTER TABLE visual_format DROP CONSTRAINT FK_A187A35DB4CB84B6');
        $this->addSql('DROP TABLE "app_user"');
        $this->addSql('DROP TABLE cinema');
        $this->addSql('DROP TABLE movie');
        $this->addSql('DROP TABLE movie_reference');
        $this->addSql('DROP TABLE movie_screening_format');
        $this->addSql('DROP TABLE reservation');
        $this->addSql('DROP TABLE reservation_seat');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('DROP TABLE screening_format');
        $this->addSql('DROP TABLE screening_room');
        $this->addSql('DROP TABLE screening_room_seat');
        $this->addSql('DROP TABLE screening_room_setup');
        $this->addSql('DROP TABLE seat');
        $this->addSql('DROP TABLE showtime');
        $this->addSql('DROP TABLE showtime_visual_format');
        $this->addSql('DROP TABLE visual_format');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
