<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250518061026 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE price_tier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(30) NOT NULL, price DOUBLE PRECISION NOT NULL, is_active BOOLEAN NOT NULL, cinema_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_59CC6530B4CB84B6 ON price_tier (cinema_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE price_tier ADD CONSTRAINT FK_59CC6530B4CB84B6 FOREIGN KEY (cinema_id) REFERENCES cinema (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE screening_room_seat ADD price_tier_id INT DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE screening_room_seat ALTER pricing_type TYPE VARCHAR(255)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE screening_room_seat ALTER pricing_type DROP DEFAULT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE screening_room_seat ADD CONSTRAINT FK_8162D54C8723180 FOREIGN KEY (price_tier_id) REFERENCES price_tier (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_8162D54C8723180 ON screening_room_seat (price_tier_id)
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE price_tier DROP CONSTRAINT FK_59CC6530B4CB84B6
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE price_tier
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE screening_room_seat DROP CONSTRAINT FK_8162D54C8723180
        SQL);
        $this->addSql(<<<'SQL'
            DROP INDEX IDX_8162D54C8723180
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE screening_room_seat DROP price_tier_id
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE screening_room_seat ALTER pricing_type TYPE VARCHAR(255)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE screening_room_seat ALTER pricing_type SET DEFAULT 'regular'
        SQL);
    }
}
