homepage:
    path: /
    controller: App\Controller\CinemaController::index

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
  
    
